<?php

namespace DBlackborough\Quill\Renderer;

/**
 * Quill renderer, converts quill delta inserts into HTML
 *
 * @author Dean Blackborough <dean@g3d-development.com>
 * @copyright Dean Blackborough
 * @license https://github.com/deanblackborough/php-quill-renderer/blob/master/LICENSE
 */
class Html extends Render
{
    /**
     * The generated HTML, string generated by the render method from the content array
     *
     * @var string
     */
    protected $html;

    /**
     * Renderer constructor.
     *
     * @param array $content Content data array
     */
    public function __construct(array $content)
    {
        $this->html = null;

        parent::__construct($content);
    }

    /**
     * Generate the final HTML from the contents array
     *
     * @return string
     */
    public function render()
    {
        foreach ($this->content as $content) {
            foreach ($content['tags'] as $tag) {
                if (array_key_exists('open', $tag) === true && $tag['open'] !== null) {
                    $this->html .= $tag['open'];
                }
            }

            $this->html .= $content['content'];

            foreach (array_reverse($content['tags']) as $tag) {
                if (array_key_exists('close', $tag) === true && $tag['close'] !== null) {
                    $this->html .= $tag['close'];
                }
            }
        }

        return $this->html;
    }
}
